version: "3.7"
x-environment: &airflow-environment
  AIRFLOW__CORE__EXECUTOR: LocalExecutor
  AIRFLOW__CORE__LOAD_EXAMPLES: "False"
  AIRFLOW__CORE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres:5432/airflow
  SQLALCHEMY_DATABASE_URI: postgresql+psycopg2://airflow:airflow@postgres:5432/airflow
  AIRFLOW_CONN_METADATA_DB: postgres+psycopg2://airflow:airflow@postgres:5432/airflow
  AIRFLOW_VAR__METADATA_DB_SCHEMA: airflow
  AIRFLOW__CORE__FERNET_KEY: ZFOPQmxjHK3x5eQzSUCRrVV6bjAYxpBzM8If_a3bpZU=
  AIRFLOW__WEBSERVER__DAG_DEFAULT_VIEW: graph
  AIRFLOW__WEBSERVER__DEFAULT_UI_TIMEZONE: CET

services:
  postgres:
    image: postgres:13-alpine
    environment:
      POSTGRES_USER: airflow
      POSTGRES_DB: airflow
      POSTGRES_PASSWORD: airflow
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - my-airflow-database:/var/lib/postgresql/data/pgdata

  init:
    build: .
    environment:
      <<: *airflow-environment
    depends_on:
      - postgres
    volumes:
      - ./scripts:/scripts
      - ./variables/variables.json:/opt/airflow/variables.json
      - my-airflow-logs:/opt/airflow/logs
    entrypoint: /bin/bash
    command: -c "bash /scripts/init.sh"
    restart: "no"

  webserver:
    build: .
    ports:
      - 8080:8080
    environment:
      <<: *airflow-environment
    depends_on:
      - init
    volumes:
      - ./dags:/opt/airflow/dags
      - my-airflow-logs:/opt/airflow/logs
    entrypoint: /bin/bash
    command: -c "airflow webserver"
    restart: always

  scheduler:
    build: .
    ports:
      - 8793:8793
    environment:
      <<: *airflow-environment
    depends_on:
      - webserver
    volumes:
      - ./dags:/opt/airflow/dags
      - my-airflow-logs:/opt/airflow/logs
    entrypoint: /bin/bash
    command: -c "airflow scheduler"
    restart: always

volumes:
  my-airflow-database:
  my-airflow-logs:

