version: "3.7"
x-airflow-environment: &airflow-environment
  AIRFLOW__CORE__EXECUTOR: LocalExecutor
  AIRFLOW__CORE__LOAD_EXAMPLES: "False"
  AIRFLOW__CORE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres:5432/airflow
  AIRFLOW__CORE__FERNET_KEY: 9o6DgC4QZPswUlFRsE6RSq9KTwIilZUSUHtDaVKFqsY=
  AIRFLOW__WEBSERVER__DAG_DEFAULT_VIEW: graph
  AIRFLOW__WEBSERVER__DEFAULT_UI_TIMEZONE: CET

services:
  postgres:
    image: postgres:11.5
    environment:
      POSTGRES_USER: airflow
      POSTGRES_DB: airflow
      POSTGRES_PASSWORD: airflow
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - my-airflow-database:/var/lib/postgresql/data/pgdata
  webserver:
    build: .
    ports:
      - 8080:8080
    environment:
      <<: *airflow-environment
    depends_on:
      - postgres
    volumes:
      - ./dags:/opt/airflow/dags
      - ./variables/variables.json:/opt/airflow/variables.json
      - my-airflow-logs:/opt/airflow/logs
    entrypoint: /bin/bash
    command: >
      -c "airflow upgradedb
      && airflow variables -i /opt/airflow/variables.json
      && airflow webserver"
    restart: always
  scheduler:
    build: .
    ports:
      - 8793:8793
    environment:
      <<: *airflow-environment
    depends_on:
      - webserver
    volumes:
      - ./dags:/opt/airflow/dags
      - my-airflow-logs:/opt/airflow/logs
    entrypoint: /bin/bash
    command: -c "airflow scheduler"
    restart: always
volumes:
  my-airflow-database:
  my-airflow-logs:

